name: build-check

on:  
  push:
    branches: [ master ]
    
jobs: 
  build:   
    runs-on: ubuntu-latest   
      
    steps:
      - uses: actions/checkout@v2     
      
      - name: Setup .NET 3.x
        uses: actions/setup-dotnet@v1
        with:        
          dotnet-version: '3.x'     
      
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./PatternsStudy

      - name: Build	
        run: dotnet build --no-restore
        working-directory: ./PatternsStudy
