name: build-check

on:  
  push:
    branches: [ master ]
    
jobs: 
  build:   
    runs-on: ubuntu-latest   
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET 3.x
        uses: actions/setup-dotnet@v1
        with:        
          dotnet-version: '3.x'     
      
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
